name: E2E Tests

on:
  # keeping this till we figure out #371, so we can at least validate the
  #   scrapper PRs aren't breaking things
  push:
    branches: [ main ]

  # https://frontside.com/blog/2020-05-26-github-actions-pull_request/
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # runs this again when there is a new tests container
  workflow_run:
    workflows: ["Building Tests Container"]
    types:
      - completed

jobs:
  e2e-tests_prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # inspired from this:
      # https://github.com/shrink/actions-docker-extract/blob/23130a485b089b4bb1e3710946034ebc90b00072/src/extract.js
      - name: run hugo build
        run: docker cp "$(docker create quay.io/elrey741/jb_web_container:prod-latest)":/usr/share/nginx/html ./public

      - name: run server
        working-directory: ./public
        run: |
          python -m http.server 1313 &

      - name: Run your tests
        uses: docker://quay.io/elrey741/jb_web_container:tests-latest
        with:
          args: --base-url http://localhost:1313 -v --junitxml report.xml

      - name: Save screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots/

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: E2E Tests
          path: './report.xml'
          reporter: java-junit
