name: E2E Tests

on:
  # keeping this till we figure out #371, so we can at least validate the
  #   scrapper PRs aren't breaking things
  push:
    branches: [ main ]

  # https://frontside.com/blog/2020-05-26-github-actions-pull_request/
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # runs this again when there is a new tests container
  workflow_run:
    workflows: ["Building Tests Container"]
    types:
      - completed

jobs:
  e2e-tests_prep:
    runs-on: ubuntu-latest
    services:
      jb-com:
        image: quay.io/elrey741/jb_web_container:prod-latest
    container:
      image: quay.io/elrey741/jb_web_container:tests-latest
      options: --user 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: change file ownership
        run: |
          chown -R "$(id -u)":"$(id -g)" "${GITHUB_WORKSPACE}/."

      - name: Run your tests
        run: pytest --base-url http://jb-com -v --junitxml report.xml
        # jb-com works as the base domain, because the service (jb-com) is a container
        #   since we're using a container to run this, then we don't need to expose any ports
        #   because they're on the same network bridge, more info here:
        #   https://docs.github.com/en/actions/using-containerized-services/about-service-containers#running-jobs-in-a-container

      - name: Save screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots/

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: E2E Tests
          path: './report.xml'
          reporter: java-junit
