name: E2E Tests

on:
  # keeping this till we figure out #371, so we can at least validate the
  #   scrapper PRs aren't breaking things
  push:
    branches: [ main ]

  # https://frontside.com/blog/2020-05-26-github-actions-pull_request/
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # runs this again when there is a new tests container
  workflow_run:
    workflows: ["Building Tests Container"]
    types:
      - completed

jobs:
  e2e-tests_prep:
    runs-on: ubuntu-latest
    services:
      jb-com:
        image: quay.io/elrey741/jb_web_container:prod-latest
        ports:
          - 8080:80/tcp
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run your tests
        uses: docker://quay.io/elrey741/jb_web_container:tests-latest
        with:
          entrypoint: curl
          args: http://jb-com:8080

      - name: Save screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots/

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: E2E Tests
          path: './report.xml'
          reporter: java-junit
